// This file is automatically generated by phluts init.

import 'package:phluts/phluts_core.dart';

/// Default [PhlutsOptions] for use with your phluts project.
///
/// Use this to initialize phluts **before** calling [runApp].
///
/// Example:
/// ```dart
/// import 'package:flutter/material.dart';
/// import 'package:phluts/phluts.dart';
/// import 'default_phluts_options.dart';
///
/// void main() {
///   Phluts.initialize(options: defaultPhlutsOptions);
///
///   runApp(...);
/// }
/// ```
PhlutsOptions get defaultPhlutsOptions => PhlutsOptions(
  name: 'movie_app',
  description: '',
  projectId: 'pha1PAyoVRqREK5M2k3E',
);
